FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm config set registry https://registry.npmmirror.com
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npx", "ts-node-dev", "--respawn", "src/server.ts"]
