export const PERMISSIONS = {
  USER_ENROLL: "user:enroll",
  USER_EDIT_SELF: "user:edit_self",
  ARTICLE_CREATE: "article:create",
  ARTICLE_READ: "article:read",
  ARTICLE_UPDATE: "article:update",
  ARTICLE_DELETE: "article:delete",
  ARTICLE_DELETE_HARD: "article:delete_hard", // 硬删除
  CATEGORY_CREATE: "category:create",
  CATEGORY_READ: "category:read",
  CATEGORY_UPDATE: "category:update",
  CATEGORY_DELETE: "category:delete", // 软删除
  CATEGORY_DELETE_HARD: "category:delete_hard", // 硬删除
  TAG_CREATE: "tag:create",
  TAG_READ: "tag:read",
  TAG_UPDATE: "tag:update",
  TAG_DELETE: "tag:delete", // 软删除
  TAG_DELETE_HARD: "tag:delete_hard", // 硬删除
};

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  admin: [
    PERMISSIONS.USER_ENROLL,
    PERMISSIONS.USER_EDIT_SELF,
    PERMISSIONS.ARTICLE_CREATE,
    PERMISSIONS.ARTICLE_READ,
    PERMISSIONS.ARTICLE_UPDATE,
    PERMISSIONS.ARTICLE_DELETE,
    PERMISSIONS.ARTICLE_DELETE_HARD,
    PERMISSIONS.CATEGORY_CREATE,
    PERMISSIONS.CATEGORY_READ,
    PERMISSIONS.CATEGORY_UPDATE,
    PERMISSIONS.CATEGORY_DELETE,
    PERMISSIONS.CATEGORY_DELETE_HARD,
    PERMISSIONS.TAG_CREATE,
    PERMISSIONS.TAG_UPDATE,
    PERMISSIONS.TAG_DELETE,
    PERMISSIONS.TAG_DELETE_HARD,
    PERMISSIONS.TAG_READ,
  ],
  editor: [
    PERMISSIONS.USER_EDIT_SELF,
    PERMISSIONS.ARTICLE_CREATE,
    PERMISSIONS.ARTICLE_READ,
    PERMISSIONS.ARTICLE_UPDATE,
    PERMISSIONS.ARTICLE_DELETE,
    PERMISSIONS.CATEGORY_READ,
    PERMISSIONS.CATEGORY_CREATE,
    PERMISSIONS.TAG_READ,
    PERMISSIONS.TAG_CREATE,
  ],
  viewer: [
    PERMISSIONS.USER_EDIT_SELF,
    PERMISSIONS.ARTICLE_READ,
    PERMISSIONS.CATEGORY_READ,
    PERMISSIONS.TAG_READ,
  ],
};
